on: [pull_request]

jobs:
  assign_me:
    runs-on: ubuntu-latest
    name: Assign-me ðŸ“„
    steps: 
      - uses: AblertHernandez/assign-me@v1.0.0
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
